import 'dart:convert';
import 'dart:io';

import 'package:flutter/services.dart' show rootBundle;
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';

import '../models/events.dart';
import 'constants.dart';

/// Loads and indexes the season fixtures.
///
/// Data source order at startup: local cache file (last successful fetch)
/// if present and valid, otherwise the bundled assets/data/events.json
/// (generated from the web app's events.ts by tool/generate_events_json.mjs).
///
/// [refresh] fetches the live feed published by the web app and, on success,
/// swaps the in-memory data and persists the raw payload to the cache file so
/// the next cold start uses it (FR-OFFLINE-2: offline starts keep the last
/// known snapshot).
class EventsRepository {
  EventsRepository._(this._byMonth, this._cacheFileProvider);

  /// URL of the live feed generated by app/scripts/generate-events-json.ts.
  static const remoteUrl = '$siteBaseUrl/events.json';

  static const _fetchTimeout = Duration(seconds: 10);
  static const _cacheFileName = 'events-cache.json';

  /// Month name (september…august) → events for that month, in source order.
  Map<String, List<SportEvent>> _byMonth;
  Map<String, List<SportEvent>> get byMonth => _byMonth;

  /// Resolves the cache file location; injectable for tests. May return null
  /// (e.g. on platforms/tests where path_provider is unavailable) — caching
  /// is then silently skipped.
  final Future<File?> Function() _cacheFileProvider;

  static Future<File?> _defaultCacheFile() async {
    try {
      final dir = await getApplicationDocumentsDirectory();
      return File('${dir.path}/$_cacheFileName');
    } catch (_) {
      return null; // Plugin unavailable (tests) — no cache.
    }
  }

  /// Loads from the cache file when present and valid, else the bundled asset.
  ///
  /// [cacheFile] overrides where the cache lives (used by tests to point at a
  /// temp directory).
  static Future<EventsRepository> load({Future<File?> Function()? cacheFile}) async {
    final provider = cacheFile ?? _defaultCacheFile;

    try {
      final file = await provider();
      if (file != null && await file.exists()) {
        final cached = _parsePayload(await file.readAsString());
        if (cached != null) return EventsRepository._(cached, provider);
      }
    } catch (_) {
      // Corrupt/unreadable cache — fall through to the bundled asset.
    }

    final raw = await rootBundle.loadString('assets/data/events.json');
    final bundled = _parsePayload(raw);
    return EventsRepository._(bundled ?? {}, provider);
  }

  /// Fetches the live feed and swaps the in-memory data on success.
  ///
  /// Returns true when new data was applied. Any failure (no network, bad
  /// status, malformed payload, timeout) returns false and leaves the current
  /// data untouched — it never throws.
  Future<bool> refresh({http.Client? client}) async {
    final c = client ?? http.Client();
    try {
      final response = await c.get(Uri.parse(remoteUrl)).timeout(_fetchTimeout);
      if (response.statusCode != 200) return false;

      final raw = utf8.decode(response.bodyBytes);
      final parsed = _parsePayload(raw);
      if (parsed == null) return false;

      _byMonth = parsed;
      _allEvents = null; // Invalidate the memoized chronological index.
      await _persist(raw);
      return true;
    } catch (_) {
      return false;
    } finally {
      if (client == null) c.close();
    }
  }

  /// Best-effort write of the raw feed payload to the cache file.
  Future<void> _persist(String raw) async {
    try {
      final file = await _cacheFileProvider();
      await file?.writeAsString(raw, flush: true);
    } catch (_) {
      // Caching is an optimisation — never let it break a refresh.
    }
  }

  /// Parses either the wrapped live-feed shape `{"events": {month: [...]}}`
  /// or a bare month map (the bundled asset). Returns null when the JSON is
  /// malformed or contains no known month key.
  static Map<String, List<SportEvent>>? _parsePayload(String raw) {
    try {
      final decoded = json.decode(raw);
      if (decoded is! Map<String, dynamic>) return null;
      final events = decoded['events'];
      final monthMap = events is Map<String, dynamic> ? events : decoded;

      final byMonth = <String, List<SportEvent>>{};
      for (final month in monthOrder) {
        final list = monthMap[month] as List?;
        if (list == null) continue;
        byMonth[month] =
            list.map((e) => SportEvent.fromJson(e as Map<String, dynamic>)).toList();
      }
      return byMonth.isEmpty ? null : byMonth;
    } catch (_) {
      return null;
    }
  }

  List<SportEvent> eventsFor(String monthName) => _byMonth[monthName] ?? const [];

  List<DatedEvent>? _allEvents;

  /// All events of the season in chronological order with resolved dates.
  /// Cached: callers (e.g. the countdown banner) invoke this every second;
  /// invalidated when [refresh] swaps the data.
  List<DatedEvent> allEvents() => _allEvents ??= _buildAllEvents();

  List<DatedEvent> _buildAllEvents() {
    final result = <DatedEvent>[];
    for (final month in monthOrder) {
      final info = monthInfo(month);
      final events = [...eventsFor(month)]..sort((a, b) => a.day.compareTo(b.day));
      for (final e in events) {
        var date = DateTime(info.year, info.month, e.day);
        if (e.time.contains(':')) {
          final parts = e.time.split(':');
          final h = int.tryParse(parts[0]);
          final m = int.tryParse(parts[1]);
          if (h != null && m != null) {
            date = DateTime(info.year, info.month, e.day, h, m);
          }
        }
        result.add(DatedEvent(monthName: month, event: e, date: date));
      }
    }
    return result;
  }

  /// The next event that hasn't kicked off yet (falls back to status when no time).
  DatedEvent? nextUpcoming(DateTime now) {
    for (final de in allEvents()) {
      if (de.event.status == MatchStatus.upcoming && de.date.add(const Duration(hours: 2)).isAfter(now)) {
        return de;
      }
    }
    return null;
  }

  /// Month containing today if within the season, otherwise the first month
  /// with an upcoming event, otherwise september.
  String initialMonth(DateTime now) {
    for (final month in monthOrder) {
      final info = monthInfo(month);
      if (info.year == now.year && info.month == now.month) return month;
    }
    final next = nextUpcoming(now);
    return next?.monthName ?? monthOrder.first;
  }
}
