import 'dart:convert';
import 'dart:io';

import 'package:flutter/services.dart' show rootBundle;
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';

import '../models/players.dart';
import 'constants.dart';

/// Loads the squad roster.
///
/// Same live-data pattern as [EventsRepository]: startup uses the local cache
/// file (last successful fetch) when present and valid, else the bundled
/// assets/data/players.json (generated from the web app's players.ts by
/// tool/generate_players_json.mjs). [refresh] fetches the live feed, swaps the
/// in-memory roster on success and persists the raw payload for the next cold
/// start. Failures are silent and keep the current data.
class PlayersRepository {
  PlayersRepository._(this._all, this._cacheFileProvider);

  /// URL of the live feed generated by app/scripts/generate-events-json.ts.
  static const remoteUrl = '$siteBaseUrl/players.json';

  static const _fetchTimeout = Duration(seconds: 10);
  static const _cacheFileName = 'players-cache.json';

  /// Full roster in source order.
  List<Player> _all;
  List<Player> get all => _all;

  /// Resolves the cache file location; injectable for tests. May return null
  /// (e.g. on platforms/tests where path_provider is unavailable) — caching
  /// is then silently skipped.
  final Future<File?> Function() _cacheFileProvider;

  static Future<File?> _defaultCacheFile() async {
    try {
      final dir = await getApplicationDocumentsDirectory();
      return File('${dir.path}/$_cacheFileName');
    } catch (_) {
      return null; // Plugin unavailable (tests) — no cache.
    }
  }

  /// Loads from the cache file when present and valid, else the bundled asset.
  ///
  /// [cacheFile] overrides where the cache lives (used by tests to point at a
  /// temp directory).
  static Future<PlayersRepository> load({Future<File?> Function()? cacheFile}) async {
    final provider = cacheFile ?? _defaultCacheFile;

    try {
      final file = await provider();
      if (file != null && await file.exists()) {
        final cached = _parsePayload(await file.readAsString());
        if (cached != null) return PlayersRepository._(cached, provider);
      }
    } catch (_) {
      // Corrupt/unreadable cache — fall through to the bundled asset.
    }

    final raw = await rootBundle.loadString('assets/data/players.json');
    final bundled = _parsePayload(raw);
    return PlayersRepository._(bundled ?? [], provider);
  }

  /// Fetches the live roster and swaps the in-memory data on success.
  ///
  /// Returns true when new data was applied. Any failure (no network, bad
  /// status, malformed payload, timeout) returns false and leaves the current
  /// roster untouched — it never throws.
  Future<bool> refresh({http.Client? client}) async {
    final c = client ?? http.Client();
    try {
      final response = await c.get(Uri.parse(remoteUrl)).timeout(_fetchTimeout);
      if (response.statusCode != 200) return false;

      final raw = utf8.decode(response.bodyBytes);
      final parsed = _parsePayload(raw);
      if (parsed == null) return false;

      _all = parsed;
      await _persist(raw);
      return true;
    } catch (_) {
      return false;
    } finally {
      if (client == null) c.close();
    }
  }

  /// Best-effort write of the raw feed payload to the cache file.
  Future<void> _persist(String raw) async {
    try {
      final file = await _cacheFileProvider();
      await file?.writeAsString(raw, flush: true);
    } catch (_) {
      // Caching is an optimisation — never let it break a refresh.
    }
  }

  /// Parses either the wrapped live-feed shape `{"players": [...]}` or a bare
  /// list (the bundled asset). Returns null when the JSON is malformed, the
  /// list is empty, or an entry is missing its key/position fields.
  static List<Player>? _parsePayload(String raw) {
    try {
      final decoded = json.decode(raw);
      final list = decoded is Map<String, dynamic> ? decoded['players'] : decoded;
      if (list is! List || list.isEmpty) return null;
      for (final entry in list) {
        if (entry is! Map<String, dynamic> ||
            entry['key'] is! String ||
            entry['position'] is! String) {
          return null;
        }
      }
      return list.map((e) => Player.fromJson(e as Map<String, dynamic>)).toList();
    } catch (_) {
      return null;
    }
  }
}
